### ISSUE TITLE
Diseño de estructura de librería DLL

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipo-mad#1]
[Reporte de Estructura de Librería DLL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipo-mad/files/14686298/Reporte.de.Estructura.de.Libreria.DLL.pdf)

Integrantes:
Marlene Maricela Osorio Ramírez
Adriana Hernández Martínez
Daniel Velasco López

**Comment by Daisy-GonzalezLita12** [comment]
20% de 20%, bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
